// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1BmjMjvFbKcC-MXxOB8MM1qMdIJBVD3E',
    appId: '1:765068655697:web:667846847086499b058c70',
    messagingSenderId: '765068655697',
    projectId: 'quizzapp-1c0d8',
    authDomain: 'quizzapp-1c0d8.firebaseapp.com',
    storageBucket: 'quizzapp-1c0d8.appspot.com',
    measurementId: 'G-XR10Q5YECX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PX0_YXjad2Lu18mfsnGsgfepyG-PAOE',
    appId: '1:765068655697:android:9b4aeabe0bd4e44c058c70',
    messagingSenderId: '765068655697',
    projectId: 'quizzapp-1c0d8',
    storageBucket: 'quizzapp-1c0d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZR0RogcM9QUEPKzgeLL5RVaXGKe0LDBo',
    appId: '1:765068655697:ios:94316e3b0b89c9f7058c70',
    messagingSenderId: '765068655697',
    projectId: 'quizzapp-1c0d8',
    storageBucket: 'quizzapp-1c0d8.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZR0RogcM9QUEPKzgeLL5RVaXGKe0LDBo',
    appId: '1:765068655697:ios:327ba5316a16a0d4058c70',
    messagingSenderId: '765068655697',
    projectId: 'quizzapp-1c0d8',
    storageBucket: 'quizzapp-1c0d8.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
